2024-02-02 12:17:19,531: root: INFO: MLTrader : Executing the initialize lifecycle method
2024-02-02 12:17:21,719: root: INFO: Current backtesting datetime 2023-11-01 08:30:00-04:00
2024-02-02 12:17:21,719: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-02 12:17:21,719: root: INFO: Current backtesting datetime 2023-11-01 09:30:00-04:00
2024-02-02 12:17:21,719: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-02 12:17:21,719: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-02 12:17:21[0m
2024-02-02 12:17:21,729: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-02 12:17:21,759: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-02 12:17:23,680: root: INFO: [34mMLTrader : Trading iteration ended at 2024-02-02 12:17:23[0m
2024-02-02 12:17:23,680: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-02 12:17:23,680: root: INFO: Current backtesting datetime 2023-11-02 09:30:00-04:00
2024-02-02 12:17:23,688: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-02 12:17:23[0m
2024-02-02 12:17:23,688: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-02 12:17:23,688: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-02 12:17:24,782: root: ERROR: create_order() got an unexpected keyword argument 'type'
2024-02-02 12:17:24,782: root: ERROR: Traceback (most recent call last):
  File "C:\Users\LENOVO\1. Projects\TradingBot\env\lib\site-packages\lumibot\strategies\strategy_executor.py", line 822, in run
    self._run_trading_session()
  File "C:\Users\LENOVO\1. Projects\TradingBot\env\lib\site-packages\lumibot\strategies\strategy_executor.py", line 773, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\LENOVO\1. Projects\TradingBot\env\lib\site-packages\lumibot\strategies\strategy_executor.py", line 286, in func_output
    result = func_input(self, *args, **kwargs)
  File "C:\Users\LENOVO\1. Projects\TradingBot\env\lib\site-packages\lumibot\strategies\strategy_executor.py", line 310, in func_output
    result = func_input(self, *args, **kwargs)
  File "C:\Users\LENOVO\1. Projects\TradingBot\env\lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
  File "C:\Users\LENOVO\1. Projects\TradingBot\env\lib\site-packages\lumibot\strategies\strategy_executor.py", line 388, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\LENOVO\1. Projects\TradingBot\env\lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\LENOVO\1. Projects\TradingBot\env\lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\LENOVO\1. Projects\TradingBot\run.py", line 73, in on_trading_iteration
    order = self.create_order(
TypeError: create_order() got an unexpected keyword argument 'type'

2024-02-02 12:17:24,782: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-02 12:17:25,188: backtest_stats: INFO: Backtest took 0:00:05.668363 for a speed of 0.000
2024-02-02 12:17:25,201: root: INFO: There were no trades in this backtest.
2024-02-02 12:17:25,425: root: ERROR: Not enough data to create a tearsheet, at least 2 days of data are required. Skipping
